name: hikomaryu
description: This is the demo for chat app by Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^0.1.3 #0.1.2
    firebase_core: ^0.5.0
    firebase_auth: ^0.18.0+1 #0.14.0+5
    google_sign_in: ^4.5.3 #4.0.7
    cloud_firestore: ^0.14.0+2 #^0.12.9+5
    fluttertoast: ^7.0.2 #3.1.3
    image_picker: ^0.6.7+7 #0.6.1+8
    shared_preferences: ^0.5.10 #0.5.3+4
    firebase_storage: ^4.0.0 #3.0.6
    cached_network_image: ^2.3.1 #2.0.0-rc.1
    intl: ^0.16.1 #0.15.7
    firebase_messaging: 7.0.0 #6.0.13
    flutter_local_notifications: 1.4.4+4 #1.4.0
    photo_view: ^0.10.2 #0.5.0
    search_choices: ^1.0.17

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_native_splash: ^0.1.9

flutter_native_splash:
    image: "images/logo.png"
    color: "#ffffff"

flutter:
    uses-material-design: true

    assets:
        - images/img_not_available.jpeg
        - images/mimi1.gif
        - images/mimi2.gif
        - images/mimi3.gif
        - images/mimi4.gif
        - images/mimi5.gif
        - images/mimi6.gif
        - images/mimi7.gif
        - images/mimi8.gif
        - images/mimi9.gif
